{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parabol.valkey.fullname" . }}
  labels:
    {{- include "parabol.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.valkey.service.port }}
      targetPort: valkey
      protocol: TCP
      name: valkey
  selector:
    {{- include "parabol.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
{{- end }}
